name: mars
version: 1.0.0

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
  - split
  - containers

executables:
  mars:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mars
      - strict

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - mars
      - hspec
